name: tflite_audio
maintainer: Michael Nguyen
description: Audio classification Tflite package for flutter (iOS & Android). Can support Google Teachable Machine models and decoded wave inputs. 
version: 0.1.6+1
homepage: https://github.com/Caldarie/flutter_tflite_audio

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_audio
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
