name: tflite_sound_classification
maintainer: Michael Nguyen
description: Audio classification Tflite package for flutter (iOS & Android).
version: 0.1.8+1
homepage: https://github.com/6phere/flutter_tflite_sound_classification

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_sound_classification
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
