name: tflite_audio
description: Tflite plugin for audio classification
version: 0.0.1
homepage: https://github.com/Caldarie/flutter_tflite_audio

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_audio
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
